### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by axelaris** [cloudfoundry/diego-windows-release#14]
While running `generate.exe` I got the following error message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x402383]

goroutine 1 [running]:
main.fillSharedSecret(0xc082391ee8, 0xc082366000, 0x25, 0x2a, 0x0)
        C:/diego-windows-release/greenhouse-install-script-generator/src/generate/generate.go:154 +0x93
main.main()
        C:/diego-windows-release/greenhouse-install-script-generator/src/generate/generate.go:127 +0xc82

goroutine 8 [runnable]:
net/http.(*persistConn).readLoop(0xc08208c0b0)
        c:/go/src/net/http/transport.go:928 +0x9d5
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc08208c0b0)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3

```
MS Windows Server 2012 R2 Standard, running on Openstack. 64Gb RAM

**Comment by axelaris** [comment]
Sorry I had to use Pivotal version, because I'm using PCF

**Comment by sbenario** [comment]
Hi @axelaris , did you get this figured out? It looks like just using the wrong version of generate.exe for your cf version.

**Comment by axelaris** [comment]
Yep, @sbenario, I had to get generate.exe from Pivotal site, not from gitub, because underlying Diego is from PCF deployment, not just CF.
